### ISSUE TITLE
Invite to join Futura Py

### ISSUE THREAD

**Issue by sumeshir26** [Futura-Py/Fluent-Python-Calculator#18]

**Comment by HuyHung1408** [comment]
Yes, @imcoderlg was DM me about this

**Comment by sumeshir26** [comment]
do you want to join, Ill send the invite to you soon

**Comment by HuyHung1408** [comment]
> do you want to join, Ill send the invite to you soon

Yes I do

**Comment by sumeshir26** [comment]
Ill also tell you how to transfer this repo over, still keeping all the stars, forks, issues, and commits

**Comment by HuyHung1408** [comment]
@sumeshir26 I have accepted the invitation

**Comment by sumeshir26** [comment]
Well, now you are a member
Which repos whould you ike to add to Futura?

**Comment by sumeshir26** [comment]
On the repo you want to transfer, click `Settings` on the top nav bar at the far right. Scroll all the way to the bottom and click `Transfer`

**Comment by HuyHung1408** [comment]
Would you like me to transfer this repo or Run one?

**Comment by sumeshir26** [comment]
Any, all, or none! it depends on your preference

**Comment by HuyHung1408** [comment]
@sumeshir26 Ok, I'm transfering 
![image](https://user-images.githubusercontent.com/86362423/161974829-82b718e4-02cc-4c0b-9531-4c348fef0866.png)

**Comment by sumeshir26** [comment]
Thabks!
