### ISSUE TITLE
Fixing all compiling issues

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/Fluent-Python-Calculator#23]
I have already opened an issue in the win32mica repo. Lets see what happens.

**Comment by not-nef** [comment]
Ok, small progress update: martinet101 recommended me to use pyinstaller instead of cx_Freeze, which is ok, but now i get an error with sv_ttk. I opened an issue in its repo. Hopefully we can get everything to work!

**Comment by HuyHung1408** [comment]
Nice fix @not-nef ! :)

**Comment by not-nef** [comment]
thanks, will open a pr in a few minutes
