### ISSUE TITLE
Remove icon?

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/Fluent-Python-Calculator#27]
I think the app would look very cool if we would remove the icon from the titlebar. Only an idea tho.

**Comment by HuyHung1408** [comment]
I used to remove the icon, but compiled through the pyinstaller will result in a blank icon on the taskbar, not sure if there's another way. You can try.

**Comment by HuyHung1408** [comment]
![20220418_060501.png](https://user-images.githubusercontent.com/86362423/163735457-227417b9-c0a2-4ecd-a125-4e5fd25b0bd8.png)

**Comment by rdbende** [comment]
Yeah, unfortunately with Tkinter it's not possible to hide the titlebar icon, but keep the taskbar icon. They can only be set together.

**Comment by not-nef** [comment]
Aww, ok
